# Generated by Django 2.2.6 on 2019-10-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
    ]
